// AUTO-GENERATED by scripts/generate-blog-index.mjs — do not edit by hand.
// Add an article by creating src/content/blog/<slug>.ts that exports `post`.
import type { BlogPost } from "@/lib/content-types";
import { post as post_a_que_edad_empezar_a_estudiar_musica } from "./a-que-edad-empezar-a-estudiar-musica";
import { post as post_academia_de_musica_o_profesor_particular } from "./academia-de-musica-o-profesor-particular";
import { post as post_acordes_basicos_de_guitarra_para_principiantes } from "./acordes-basicos-de-guitarra-para-principiantes";
import { post as post_admision_licenciatura_en_musica_universidad_pedagogica } from "./admision-licenciatura-en-musica-universidad-pedagogica";
import { post as post_admision_musica_universidad_de_los_andes } from "./admision-musica-universidad-de-los-andes";
import { post as post_admision_musica_universidad_distrital_asab } from "./admision-musica-universidad-distrital-asab";
import { post as post_admision_musica_universidad_javeriana } from "./admision-musica-universidad-javeriana";
import { post as post_aprender_a_cantar_de_adulto } from "./aprender-a-cantar-de-adulto";
import { post as post_aprender_guitarra_de_adulto } from "./aprender-guitarra-de-adulto";
import { post as post_aprender_musica_con_youtube_o_con_profesor } from "./aprender-musica-con-youtube-o-con-profesor";
import { post as post_aprender_musica_en_familia_o_en_pareja } from "./aprender-musica-en-familia-o-en-pareja";
import { post as post_aprender_musica_en_la_tercera_edad_nunca_es_tarde } from "./aprender-musica-en-la-tercera-edad-nunca-es-tarde";
import { post as post_aprender_musica_para_manejar_el_estres } from "./aprender-musica-para-manejar-el-estres";
import { post as post_aprender_piano_de_adulto } from "./aprender-piano-de-adulto";
import { post as post_aprender_violin_de_adulto } from "./aprender-violin-de-adulto";
import { post as post_bandas_de_viento_en_colombia_como_empezar } from "./bandas-de-viento-en-colombia-como-empezar";
import { post as post_bateria_o_percusion_latina } from "./bateria-o-percusion-latina";
import { post as post_bateria_para_ninos_guia_para_padres } from "./bateria-para-ninos-guia-para-padres";
import { post as post_beneficios_de_aprender_guitarra } from "./beneficios-de-aprender-guitarra";
import { post as post_beneficios_de_aprender_piano } from "./beneficios-de-aprender-piano";
import { post as post_beneficios_de_aprender_un_instrumento_para_adultos_mayores } from "./beneficios-de-aprender-un-instrumento-para-adultos-mayores";
import { post as post_beneficios_de_aprender_violin } from "./beneficios-de-aprender-violin";
import { post as post_beneficios_de_cantar_y_tomar_clases_de_canto } from "./beneficios-de-cantar-y-tomar-clases-de-canto";
import { post as post_beneficios_de_la_musica_en_los_ninos } from "./beneficios-de-la-musica-en-los-ninos";
import { post as post_beneficios_de_tocar_bateria_y_percusion } from "./beneficios-de-tocar-bateria-y-percusion";
import { post as post_canas_para_clarinete_y_saxofon_como_elegir_la_dureza } from "./canas-para-clarinete-y-saxofon-como-elegir-la-dureza";
import { post as post_canciones_colombianas_para_aprender_en_tiple_o_guitarra } from "./canciones-colombianas-para-aprender-en-tiple-o-guitarra";
import { post as post_canciones_faciles_para_empezar_a_cantar } from "./canciones-faciles-para-empezar-a-cantar";
import { post as post_canciones_faciles_para_guitarra_principiantes } from "./canciones-faciles-para-guitarra-principiantes";
import { post as post_canciones_faciles_para_piano_principiantes } from "./canciones-faciles-para-piano-principiantes";
import { post as post_canciones_infantiles_para_aprender_un_instrumento } from "./canciones-infantiles-para-aprender-un-instrumento";
import { post as post_canto_lirico_o_canto_popular } from "./canto-lirico-o-canto-popular";
import { post as post_canto_para_ninos_como_cuidar_su_voz } from "./canto-para-ninos-como-cuidar-su-voz";
import { post as post_carreras_de_musica_en_colombia } from "./carreras-de-musica-en-colombia";
import { post as post_circulo_de_quintas_explicado } from "./circulo-de-quintas-explicado";
import { post as post_clase_muestra_como_evaluar_a_un_profesor_de_musica } from "./clase-muestra-como-evaluar-a-un-profesor-de-musica";
import { post as post_clases_de_musica_a_domicilio_o_virtuales } from "./clases-de-musica-a-domicilio-o-virtuales";
import { post as post_clases_de_musica_a_domicilio_que_esperar } from "./clases-de-musica-a-domicilio-que-esperar";
import { post as post_clases_de_musica_como_regalo_para_papa_mama_o_abuelos } from "./clases-de-musica-como-regalo-para-papa-mama-o-abuelos";
import { post as post_clases_de_musica_hibridas_virtual_y_presencial } from "./clases-de-musica-hibridas-virtual-y-presencial";
import { post as post_clases_de_musica_individuales_o_grupales } from "./clases-de-musica-individuales-o-grupales";
import { post as post_clases_de_musica_para_adolescentes } from "./clases-de-musica-para-adolescentes";
import { post as post_clases_de_musica_para_ninos_con_autismo } from "./clases-de-musica-para-ninos-con-autismo";
import { post as post_clases_de_musica_para_ninos_de_3_anos } from "./clases-de-musica-para-ninos-de-3-anos";
import { post as post_clases_de_musica_para_ninos_de_4_y_5_anos } from "./clases-de-musica-para-ninos-de-4-y-5-anos";
import { post as post_clases_de_musica_para_ninos_de_6_a_8_anos } from "./clases-de-musica-para-ninos-de-6-a-8-anos";
import { post as post_clases_de_musica_para_ninos_de_9_a_12_anos } from "./clases-de-musica-para-ninos-de-9-a-12-anos";
import { post as post_como_acompanar_a_tu_hijo_en_clases_virtuales_de_musica } from "./como-acompanar-a-tu-hijo-en-clases-virtuales-de-musica";
import { post as post_como_afinar_el_bajo_electrico } from "./como-afinar-el-bajo-electrico";
import { post as post_como_afinar_el_tiple } from "./como-afinar-el-tiple";
import { post as post_como_afinar_el_violin } from "./como-afinar-el-violin";
import { post as post_como_afinar_el_violonchelo } from "./como-afinar-el-violonchelo";
import { post as post_como_afinar_la_guitarra } from "./como-afinar-la-guitarra";
import { post as post_como_ampliar_el_registro_vocal } from "./como-ampliar-el-registro-vocal";
import { post as post_como_aprender_musica_desde_cero } from "./como-aprender-musica-desde-cero";
import { post as post_como_cambiar_las_cuerdas_de_la_guitarra } from "./como-cambiar-las-cuerdas-de-la-guitarra";
import { post as post_como_cantar_afinado } from "./como-cantar-afinado";
import { post as post_como_cantar_sin_lastimar_la_garganta } from "./como-cantar-sin-lastimar-la-garganta";
import { post as post_como_componer_una_cancion_desde_cero } from "./como-componer-una-cancion-desde-cero";
import { post as post_como_contratar_profesores_de_musica_para_tu_academia } from "./como-contratar-profesores-de-musica-para-tu-academia";
import { post as post_como_cuidar_la_voz_guia_para_cantantes } from "./como-cuidar-la-voz-guia-para-cantantes";
import { post as post_como_cuidar_un_bajo_electrico } from "./como-cuidar-un-bajo-electrico";
import { post as post_como_cuidar_un_contrabajo } from "./como-cuidar-un-contrabajo";
import { post as post_como_cuidar_un_oboe_y_sus_canas } from "./como-cuidar-un-oboe-y-sus-canas";
import { post as post_como_cuidar_un_tiple_y_una_bandola } from "./como-cuidar-un-tiple-y-una-bandola";
import { post as post_como_cuidar_un_violonchelo } from "./como-cuidar-un-violonchelo";
import { post as post_como_cuidar_una_bateria_y_los_instrumentos_de_percusion } from "./como-cuidar-una-bateria-y-los-instrumentos-de-percusion";
import { post as post_como_cuidar_y_limpiar_un_piano } from "./como-cuidar-y-limpiar-un-piano";
import { post as post_como_dar_clases_de_musica_particulares } from "./como-dar-clases-de-musica-particulares";
import { post as post_como_elegir_profesor_de_musica } from "./como-elegir-profesor-de-musica";
import { post as post_como_elegir_tu_primer_bajo_electrico } from "./como-elegir-tu-primer-bajo-electrico";
import { post as post_como_elegir_tu_primer_clarinete } from "./como-elegir-tu-primer-clarinete";
import { post as post_como_elegir_tu_primer_piano_o_teclado } from "./como-elegir-tu-primer-piano-o-teclado";
import { post as post_como_elegir_tu_primer_saxofon } from "./como-elegir-tu-primer-saxofon";
import { post as post_como_elegir_tu_primer_trombon } from "./como-elegir-tu-primer-trombon";
import { post as post_como_elegir_tu_primer_violin_y_su_tamano } from "./como-elegir-tu-primer-violin-y-su-tamano";
import { post as post_como_elegir_tu_primer_violonchelo } from "./como-elegir-tu-primer-violonchelo";
import { post as post_como_elegir_tu_primera_flauta_traversa } from "./como-elegir-tu-primera-flauta-traversa";
import { post as post_como_elegir_tu_primera_guitarra_acustica } from "./como-elegir-tu-primera-guitarra-acustica";
import { post as post_como_elegir_tu_primera_guitarra_electrica } from "./como-elegir-tu-primera-guitarra-electrica";
import { post as post_como_elegir_tu_primera_trompeta } from "./como-elegir-tu-primera-trompeta";
import { post as post_como_elegir_un_contrabajo_para_empezar } from "./como-elegir-un-contrabajo-para-empezar";
import { post as post_como_elegir_un_tiple_o_una_bandola } from "./como-elegir-un-tiple-o-una-bandola";
import { post as post_como_elegir_una_bateria_o_cajon_para_empezar } from "./como-elegir-una-bateria-o-cajon-para-empezar";
import { post as post_como_elegir_una_flauta_dulce } from "./como-elegir-una-flauta-dulce";
import { post as post_como_empezar_a_improvisar } from "./como-empezar-a-improvisar";
import { post as post_como_entrenar_el_oido_musical } from "./como-entrenar-el-oido-musical";
import { post as post_como_escribir_una_vacante_de_profesor_de_musica } from "./como-escribir-una-vacante-de-profesor-de-musica";
import { post as post_como_guardar_instrumentos_humedad_y_clima_en_colombia } from "./como-guardar-instrumentos-humedad-y-clima-en-colombia";
import { post as post_como_hacer_la_cejilla_en_guitarra } from "./como-hacer-la-cejilla-en-guitarra";
import { post as post_como_hacer_vibrato_en_el_violin } from "./como-hacer-vibrato-en-el-violin";
import { post as post_como_leer_la_clave_de_fa } from "./como-leer-la-clave-de-fa";
import { post as post_como_leer_partituras_guia_para_principiantes } from "./como-leer-partituras-guia-para-principiantes";
import { post as post_como_leer_tablaturas_de_guitarra_y_bajo } from "./como-leer-tablaturas-de-guitarra-y-bajo";
import { post as post_como_limpiar_un_saxofon } from "./como-limpiar-un-saxofon";
import { post as post_como_limpiar_un_trombon } from "./como-limpiar-un-trombon";
import { post as post_como_limpiar_una_flauta_dulce } from "./como-limpiar-una-flauta-dulce";
import { post as post_como_limpiar_una_flauta_traversa } from "./como-limpiar-una-flauta-traversa";
import { post as post_como_limpiar_una_trompeta } from "./como-limpiar-una-trompeta";
import { post as post_como_limpiar_y_cuidar_un_clarinete } from "./como-limpiar-y-cuidar-un-clarinete";
import { post as post_como_limpiar_y_cuidar_un_violin } from "./como-limpiar-y-cuidar-un-violin";
import { post as post_como_limpiar_y_cuidar_una_guitarra_acustica } from "./como-limpiar-y-cuidar-una-guitarra-acustica";
import { post as post_como_limpiar_y_cuidar_una_guitarra_electrica } from "./como-limpiar-y-cuidar-una-guitarra-electrica";
import { post as post_como_memorizar_una_pieza_musical } from "./como-memorizar-una-pieza-musical";
import { post as post_como_motivar_a_tu_hijo_a_practicar_su_instrumento } from "./como-motivar-a-tu-hijo-a-practicar-su-instrumento";
import { post as post_como_organizar_el_area_de_musica_de_un_colegio } from "./como-organizar-el-area-de-musica-de-un-colegio";
import { post as post_como_poner_los_dedos_en_el_violin } from "./como-poner-los-dedos-en-el-violin";
import { post as post_como_practicar_musica_en_casa } from "./como-practicar-musica-en-casa";
import { post as post_como_preparar_tu_espacio_para_clases_virtuales_de_musica } from "./como-preparar-tu-espacio-para-clases-virtuales-de-musica";
import { post as post_como_preparar_una_clase_de_musica } from "./como-preparar-una-clase-de-musica";
import { post as post_como_prepararte_para_la_prueba_de_admision_de_musica } from "./como-prepararte-para-la-prueba-de-admision-de-musica";
import { post as post_como_prepararte_para_tu_primer_recital } from "./como-prepararte-para-tu-primer-recital";
import { post as post_como_proteger_tu_audicion_si_eres_musico } from "./como-proteger-tu-audicion-si-eres-musico";
import { post as post_como_retener_a_los_profesores_de_tu_academia } from "./como-retener-a-los-profesores-de-tu-academia";
import { post as post_como_saber_mi_tipo_de_voz } from "./como-saber-mi-tipo-de-voz";
import { post as post_como_sacar_sonido_en_la_flauta_traversa } from "./como-sacar-sonido-en-la-flauta-traversa";
import { post as post_como_ser_profesor_de_musica_en_colombia } from "./como-ser-profesor-de-musica-en-colombia";
import { post as post_como_sostener_el_arco_del_violin } from "./como-sostener-el-arco-del-violin";
import { post as post_como_transportar_una_cancion } from "./como-transportar-una-cancion";
import { post as post_como_usar_el_metronomo_para_practicar } from "./como-usar-el-metronomo-para-practicar";
import { post as post_como_usar_el_pedal_del_piano } from "./como-usar-el-pedal-del-piano";
import { post as post_como_vencer_el_miedo_escenico } from "./como-vencer-el-miedo-escenico";
import { post as post_compases_musicales_explicados_2_4_3_4_4_4_y_6_8 } from "./compases-musicales-explicados-2-4-3-4-4-4-y-6-8";
import { post as post_cuantas_horas_practicar_al_dia } from "./cuantas-horas-practicar-al-dia";
import { post as post_cuanto_cuestan_las_clases_de_musica_que_influye_en_el_precio } from "./cuanto-cuestan-las-clases-de-musica-que-influye-en-el-precio";
import { post as post_cuanto_tiempo_toma_aprender_a_cantar } from "./cuanto-tiempo-toma-aprender-a-cantar";
import { post as post_cuanto_tiempo_toma_aprender_a_leer_partituras } from "./cuanto-tiempo-toma-aprender-a-leer-partituras";
import { post as post_cuanto_tiempo_toma_aprender_bajo_electrico } from "./cuanto-tiempo-toma-aprender-bajo-electrico";
import { post as post_cuanto_tiempo_toma_aprender_bateria } from "./cuanto-tiempo-toma-aprender-bateria";
import { post as post_cuanto_tiempo_toma_aprender_clarinete } from "./cuanto-tiempo-toma-aprender-clarinete";
import { post as post_cuanto_tiempo_toma_aprender_flauta_traversa } from "./cuanto-tiempo-toma-aprender-flauta-traversa";
import { post as post_cuanto_tiempo_toma_aprender_guitarra } from "./cuanto-tiempo-toma-aprender-guitarra";
import { post as post_cuanto_tiempo_toma_aprender_piano } from "./cuanto-tiempo-toma-aprender-piano";
import { post as post_cuanto_tiempo_toma_aprender_saxofon } from "./cuanto-tiempo-toma-aprender-saxofon";
import { post as post_cuanto_tiempo_toma_aprender_tiple } from "./cuanto-tiempo-toma-aprender-tiple";
import { post as post_cuanto_tiempo_toma_aprender_trompeta } from "./cuanto-tiempo-toma-aprender-trompeta";
import { post as post_cuanto_tiempo_toma_aprender_violin } from "./cuanto-tiempo-toma-aprender-violin";
import { post as post_cuanto_tiempo_toma_aprender_violonchelo } from "./cuanto-tiempo-toma-aprender-violonchelo";
import { post as post_dictado_musical_como_prepararlo } from "./dictado-musical-como-prepararlo";
import { post as post_dolor_en_los_dedos_al_tocar_guitarra } from "./dolor-en-los-dedos-al-tocar-guitarra";
import { post as post_ejercicios_de_calentamiento_vocal } from "./ejercicios-de-calentamiento-vocal";
import { post as post_ejercicios_de_independencia_de_manos_en_el_piano } from "./ejercicios-de-independencia-de-manos-en-el-piano";
import { post as post_ejercicios_de_respiracion_para_cantar } from "./ejercicios-de-respiracion-para-cantar";
import { post as post_embocadura_de_trompeta_como_empezar } from "./embocadura-de-trompeta-como-empezar";
import { post as post_entrevista_de_admision_en_musica } from "./entrevista-de-admision-en-musica";
import { post as post_equipo_para_clases_virtuales_de_musica_camara_microfono } from "./equipo-para-clases-virtuales-de-musica-camara-microfono";
import { post as post_es_tarde_para_aprender_musica_a_los_30_40_o_50 } from "./es-tarde-para-aprender-musica-a-los-30-40-o-50";
import { post as post_escalas_mayores_y_menores_explicadas } from "./escalas-mayores-y-menores-explicadas";
import { post as post_estudiar_musica_en_medellin_cali_y_otras_ciudades } from "./estudiar-musica-en-medellin-cali-y-otras-ciudades";
import { post as post_examen_de_admision_musica_universidad_nacional } from "./examen-de-admision-musica-universidad-nacional";
import { post as post_flauta_traversa_o_clarinete } from "./flauta-traversa-o-clarinete";
import { post as post_guitarra_acustica_o_electrica_cual_aprender_primero } from "./guitarra-acustica-o-electrica-cual-aprender-primero";
import { post as post_guitarra_o_bajo_cual_aprender } from "./guitarra-o-bajo-cual-aprender";
import { post as post_guitarra_o_tiple } from "./guitarra-o-tiple";
import { post as post_guitarra_para_ninos_guia_para_padres } from "./guitarra-para-ninos-guia-para-padres";
import { post as post_instrumento_nuevo_o_usado_que_revisar_antes_de_comprar } from "./instrumento-nuevo-o-usado-que-revisar-antes-de-comprar";
import { post as post_instrumentos_de_la_musica_del_caribe_colombiano } from "./instrumentos-de-la-musica-del-caribe-colombiano";
import { post as post_instrumentos_tipicos_de_colombia } from "./instrumentos-tipicos-de-colombia";
import { post as post_juegos_musicales_para_ninos_en_casa } from "./juegos-musicales-para-ninos-en-casa";
import { post as post_lectura_ritmica_y_melodica_para_la_prueba_de_admision } from "./lectura-ritmica-y-melodica-para-la-prueba-de-admision";
import { post as post_maestro_en_musica_o_licenciatura_en_musica } from "./maestro-en-musica-o-licenciatura-en-musica";
import { post as post_mi_hijo_quiere_dejar_el_instrumento_que_hacer } from "./mi-hijo-quiere-dejar-el-instrumento-que-hacer";
import { post as post_microfono_para_cantar_en_casa_como_elegir } from "./microfono-para-cantar-en-casa-como-elegir";
import { post as post_modos_griegos_explicados } from "./modos-griegos-explicados";
import { post as post_musica_andina_colombiana_guia_para_empezar } from "./musica-andina-colombiana-guia-para-empezar";
import { post as post_musica_para_bebes_estimulacion_musical_de_0_a_2_anos } from "./musica-para-bebes-estimulacion-musical-de-0-a-2-anos";
import { post as post_musica_y_tdah_como_apoyar_el_aprendizaje } from "./musica-y-tdah-como-apoyar-el-aprendizaje";
import { post as post_oido_absoluto_y_oido_relativo } from "./oido-absoluto-y-oido-relativo";
import { post as post_piano_digital_o_teclado_diferencias } from "./piano-digital-o-teclado-diferencias";
import { post as post_piano_o_guitarra_primer_instrumento } from "./piano-o-guitarra-primer-instrumento";
import { post as post_piano_para_ninos_guia_para_padres } from "./piano-para-ninos-guia-para-padres";
import { post as post_por_que_aprender_bajo_electrico } from "./por-que-aprender-bajo-electrico";
import { post as post_por_que_aprender_clarinete_u_oboe } from "./por-que-aprender-clarinete-u-oboe";
import { post as post_por_que_aprender_contrabajo } from "./por-que-aprender-contrabajo";
import { post as post_por_que_aprender_flauta_traversa } from "./por-que-aprender-flauta-traversa";
import { post as post_por_que_aprender_saxofon } from "./por-que-aprender-saxofon";
import { post as post_por_que_aprender_teoria_musical } from "./por-que-aprender-teoria-musical";
import { post as post_por_que_aprender_tiple_y_bandola_musica_andina } from "./por-que-aprender-tiple-y-bandola-musica-andina";
import { post as post_por_que_aprender_trompeta_o_trombon } from "./por-que-aprender-trompeta-o-trombon";
import { post as post_por_que_aprender_violonchelo } from "./por-que-aprender-violonchelo";
import { post as post_por_que_tomar_clases_de_musica_online } from "./por-que-tomar-clases-de-musica-online";
import { post as post_posicion_correcta_de_las_manos_en_el_piano } from "./posicion-correcta-de-las-manos-en-el-piano";
import { post as post_postura_y_ergonomia_para_musicos_evitar_lesiones } from "./postura-y-ergonomia-para-musicos-evitar-lesiones";
import { post as post_preguntas_de_entrevista_para_profesor_de_musica } from "./preguntas-de-entrevista-para-profesor-de-musica";
import { post as post_preuniversitario_de_musica_que_es } from "./preuniversitario-de-musica-que-es";
import { post as post_primeras_clases_de_canto_que_esperar } from "./primeras-clases-de-canto-que-esperar";
import { post as post_primeros_ritmos_de_bateria } from "./primeros-ritmos-de-bateria";
import { post as post_profesores_de_musica_para_jornada_complementaria } from "./profesores-de-musica-para-jornada-complementaria";
import { post as post_que_es_el_solfeo_y_como_practicarlo } from "./que-es-el-solfeo-y-como-practicarlo";
import { post as post_que_es_la_armonia_musical } from "./que-es-la-armonia-musical";
import { post as post_que_es_la_iniciacion_musical } from "./que-es-la-iniciacion-musical";
import { post as post_que_es_un_intervalo_musical } from "./que-es-un-intervalo-musical";
import { post as post_que_instrumento_aprender_despues_de_los_60 } from "./que-instrumento-aprender-despues-de-los-60";
import { post as post_que_instrumento_elegir_para_mi_hijo } from "./que-instrumento-elegir-para-mi-hijo";
import { post as post_regalos_musicales_para_ninos } from "./regalos-musicales-para-ninos";
import { post as post_repertorio_para_la_audicion_de_admision } from "./repertorio-para-la-audicion-de-admision";
import { post as post_respiracion_para_instrumentos_de_viento } from "./respiracion-para-instrumentos-de-viento";
import { post as post_ritmos_colombianos_bambuco_pasillo_y_cumbia_explicados } from "./ritmos-colombianos-bambuco-pasillo-y-cumbia-explicados";
import { post as post_ritmos_de_guitarra_rasgueos_basicos } from "./ritmos-de-guitarra-rasgueos-basicos";
import { post as post_rubrica_de_evaluacion_docente_para_profesores_de_musica } from "./rubrica-de-evaluacion-docente-para-profesores-de-musica";
import { post as post_rudimentos_de_bateria_para_principiantes } from "./rudimentos-de-bateria-para-principiantes";
import { post as post_saxofon_alto_o_tenor_para_empezar } from "./saxofon-alto-o-tenor-para-empezar";
import { post as post_trompeta_o_trombon } from "./trompeta-o-trombon";
import { post as post_verificaciones_antes_de_contratar_profesores_colombia } from "./verificaciones-antes-de-contratar-profesores-colombia";
import { post as post_villancicos_faciles_para_aprender_en_navidad } from "./villancicos-faciles-para-aprender-en-navidad";
import { post as post_violin_o_viola_diferencias } from "./violin-o-viola-diferencias";
import { post as post_violin_o_violonchelo_cual_elegir } from "./violin-o-violonchelo-cual-elegir";
import { post as post_violin_para_ninos_guia_para_padres } from "./violin-para-ninos-guia-para-padres";
import { post as post_voz_de_pecho_voz_de_cabeza_y_falsete } from "./voz-de-pecho-voz-de-cabeza-y-falsete";

export const BLOG_POST_ENTRIES: BlogPost[] = [
  post_a_que_edad_empezar_a_estudiar_musica,
  post_academia_de_musica_o_profesor_particular,
  post_acordes_basicos_de_guitarra_para_principiantes,
  post_admision_licenciatura_en_musica_universidad_pedagogica,
  post_admision_musica_universidad_de_los_andes,
  post_admision_musica_universidad_distrital_asab,
  post_admision_musica_universidad_javeriana,
  post_aprender_a_cantar_de_adulto,
  post_aprender_guitarra_de_adulto,
  post_aprender_musica_con_youtube_o_con_profesor,
  post_aprender_musica_en_familia_o_en_pareja,
  post_aprender_musica_en_la_tercera_edad_nunca_es_tarde,
  post_aprender_musica_para_manejar_el_estres,
  post_aprender_piano_de_adulto,
  post_aprender_violin_de_adulto,
  post_bandas_de_viento_en_colombia_como_empezar,
  post_bateria_o_percusion_latina,
  post_bateria_para_ninos_guia_para_padres,
  post_beneficios_de_aprender_guitarra,
  post_beneficios_de_aprender_piano,
  post_beneficios_de_aprender_un_instrumento_para_adultos_mayores,
  post_beneficios_de_aprender_violin,
  post_beneficios_de_cantar_y_tomar_clases_de_canto,
  post_beneficios_de_la_musica_en_los_ninos,
  post_beneficios_de_tocar_bateria_y_percusion,
  post_canas_para_clarinete_y_saxofon_como_elegir_la_dureza,
  post_canciones_colombianas_para_aprender_en_tiple_o_guitarra,
  post_canciones_faciles_para_empezar_a_cantar,
  post_canciones_faciles_para_guitarra_principiantes,
  post_canciones_faciles_para_piano_principiantes,
  post_canciones_infantiles_para_aprender_un_instrumento,
  post_canto_lirico_o_canto_popular,
  post_canto_para_ninos_como_cuidar_su_voz,
  post_carreras_de_musica_en_colombia,
  post_circulo_de_quintas_explicado,
  post_clase_muestra_como_evaluar_a_un_profesor_de_musica,
  post_clases_de_musica_a_domicilio_o_virtuales,
  post_clases_de_musica_a_domicilio_que_esperar,
  post_clases_de_musica_como_regalo_para_papa_mama_o_abuelos,
  post_clases_de_musica_hibridas_virtual_y_presencial,
  post_clases_de_musica_individuales_o_grupales,
  post_clases_de_musica_para_adolescentes,
  post_clases_de_musica_para_ninos_con_autismo,
  post_clases_de_musica_para_ninos_de_3_anos,
  post_clases_de_musica_para_ninos_de_4_y_5_anos,
  post_clases_de_musica_para_ninos_de_6_a_8_anos,
  post_clases_de_musica_para_ninos_de_9_a_12_anos,
  post_como_acompanar_a_tu_hijo_en_clases_virtuales_de_musica,
  post_como_afinar_el_bajo_electrico,
  post_como_afinar_el_tiple,
  post_como_afinar_el_violin,
  post_como_afinar_el_violonchelo,
  post_como_afinar_la_guitarra,
  post_como_ampliar_el_registro_vocal,
  post_como_aprender_musica_desde_cero,
  post_como_cambiar_las_cuerdas_de_la_guitarra,
  post_como_cantar_afinado,
  post_como_cantar_sin_lastimar_la_garganta,
  post_como_componer_una_cancion_desde_cero,
  post_como_contratar_profesores_de_musica_para_tu_academia,
  post_como_cuidar_la_voz_guia_para_cantantes,
  post_como_cuidar_un_bajo_electrico,
  post_como_cuidar_un_contrabajo,
  post_como_cuidar_un_oboe_y_sus_canas,
  post_como_cuidar_un_tiple_y_una_bandola,
  post_como_cuidar_un_violonchelo,
  post_como_cuidar_una_bateria_y_los_instrumentos_de_percusion,
  post_como_cuidar_y_limpiar_un_piano,
  post_como_dar_clases_de_musica_particulares,
  post_como_elegir_profesor_de_musica,
  post_como_elegir_tu_primer_bajo_electrico,
  post_como_elegir_tu_primer_clarinete,
  post_como_elegir_tu_primer_piano_o_teclado,
  post_como_elegir_tu_primer_saxofon,
  post_como_elegir_tu_primer_trombon,
  post_como_elegir_tu_primer_violin_y_su_tamano,
  post_como_elegir_tu_primer_violonchelo,
  post_como_elegir_tu_primera_flauta_traversa,
  post_como_elegir_tu_primera_guitarra_acustica,
  post_como_elegir_tu_primera_guitarra_electrica,
  post_como_elegir_tu_primera_trompeta,
  post_como_elegir_un_contrabajo_para_empezar,
  post_como_elegir_un_tiple_o_una_bandola,
  post_como_elegir_una_bateria_o_cajon_para_empezar,
  post_como_elegir_una_flauta_dulce,
  post_como_empezar_a_improvisar,
  post_como_entrenar_el_oido_musical,
  post_como_escribir_una_vacante_de_profesor_de_musica,
  post_como_guardar_instrumentos_humedad_y_clima_en_colombia,
  post_como_hacer_la_cejilla_en_guitarra,
  post_como_hacer_vibrato_en_el_violin,
  post_como_leer_la_clave_de_fa,
  post_como_leer_partituras_guia_para_principiantes,
  post_como_leer_tablaturas_de_guitarra_y_bajo,
  post_como_limpiar_un_saxofon,
  post_como_limpiar_un_trombon,
  post_como_limpiar_una_flauta_dulce,
  post_como_limpiar_una_flauta_traversa,
  post_como_limpiar_una_trompeta,
  post_como_limpiar_y_cuidar_un_clarinete,
  post_como_limpiar_y_cuidar_un_violin,
  post_como_limpiar_y_cuidar_una_guitarra_acustica,
  post_como_limpiar_y_cuidar_una_guitarra_electrica,
  post_como_memorizar_una_pieza_musical,
  post_como_motivar_a_tu_hijo_a_practicar_su_instrumento,
  post_como_organizar_el_area_de_musica_de_un_colegio,
  post_como_poner_los_dedos_en_el_violin,
  post_como_practicar_musica_en_casa,
  post_como_preparar_tu_espacio_para_clases_virtuales_de_musica,
  post_como_preparar_una_clase_de_musica,
  post_como_prepararte_para_la_prueba_de_admision_de_musica,
  post_como_prepararte_para_tu_primer_recital,
  post_como_proteger_tu_audicion_si_eres_musico,
  post_como_retener_a_los_profesores_de_tu_academia,
  post_como_saber_mi_tipo_de_voz,
  post_como_sacar_sonido_en_la_flauta_traversa,
  post_como_ser_profesor_de_musica_en_colombia,
  post_como_sostener_el_arco_del_violin,
  post_como_transportar_una_cancion,
  post_como_usar_el_metronomo_para_practicar,
  post_como_usar_el_pedal_del_piano,
  post_como_vencer_el_miedo_escenico,
  post_compases_musicales_explicados_2_4_3_4_4_4_y_6_8,
  post_cuantas_horas_practicar_al_dia,
  post_cuanto_cuestan_las_clases_de_musica_que_influye_en_el_precio,
  post_cuanto_tiempo_toma_aprender_a_cantar,
  post_cuanto_tiempo_toma_aprender_a_leer_partituras,
  post_cuanto_tiempo_toma_aprender_bajo_electrico,
  post_cuanto_tiempo_toma_aprender_bateria,
  post_cuanto_tiempo_toma_aprender_clarinete,
  post_cuanto_tiempo_toma_aprender_flauta_traversa,
  post_cuanto_tiempo_toma_aprender_guitarra,
  post_cuanto_tiempo_toma_aprender_piano,
  post_cuanto_tiempo_toma_aprender_saxofon,
  post_cuanto_tiempo_toma_aprender_tiple,
  post_cuanto_tiempo_toma_aprender_trompeta,
  post_cuanto_tiempo_toma_aprender_violin,
  post_cuanto_tiempo_toma_aprender_violonchelo,
  post_dictado_musical_como_prepararlo,
  post_dolor_en_los_dedos_al_tocar_guitarra,
  post_ejercicios_de_calentamiento_vocal,
  post_ejercicios_de_independencia_de_manos_en_el_piano,
  post_ejercicios_de_respiracion_para_cantar,
  post_embocadura_de_trompeta_como_empezar,
  post_entrevista_de_admision_en_musica,
  post_equipo_para_clases_virtuales_de_musica_camara_microfono,
  post_es_tarde_para_aprender_musica_a_los_30_40_o_50,
  post_escalas_mayores_y_menores_explicadas,
  post_estudiar_musica_en_medellin_cali_y_otras_ciudades,
  post_examen_de_admision_musica_universidad_nacional,
  post_flauta_traversa_o_clarinete,
  post_guitarra_acustica_o_electrica_cual_aprender_primero,
  post_guitarra_o_bajo_cual_aprender,
  post_guitarra_o_tiple,
  post_guitarra_para_ninos_guia_para_padres,
  post_instrumento_nuevo_o_usado_que_revisar_antes_de_comprar,
  post_instrumentos_de_la_musica_del_caribe_colombiano,
  post_instrumentos_tipicos_de_colombia,
  post_juegos_musicales_para_ninos_en_casa,
  post_lectura_ritmica_y_melodica_para_la_prueba_de_admision,
  post_maestro_en_musica_o_licenciatura_en_musica,
  post_mi_hijo_quiere_dejar_el_instrumento_que_hacer,
  post_microfono_para_cantar_en_casa_como_elegir,
  post_modos_griegos_explicados,
  post_musica_andina_colombiana_guia_para_empezar,
  post_musica_para_bebes_estimulacion_musical_de_0_a_2_anos,
  post_musica_y_tdah_como_apoyar_el_aprendizaje,
  post_oido_absoluto_y_oido_relativo,
  post_piano_digital_o_teclado_diferencias,
  post_piano_o_guitarra_primer_instrumento,
  post_piano_para_ninos_guia_para_padres,
  post_por_que_aprender_bajo_electrico,
  post_por_que_aprender_clarinete_u_oboe,
  post_por_que_aprender_contrabajo,
  post_por_que_aprender_flauta_traversa,
  post_por_que_aprender_saxofon,
  post_por_que_aprender_teoria_musical,
  post_por_que_aprender_tiple_y_bandola_musica_andina,
  post_por_que_aprender_trompeta_o_trombon,
  post_por_que_aprender_violonchelo,
  post_por_que_tomar_clases_de_musica_online,
  post_posicion_correcta_de_las_manos_en_el_piano,
  post_postura_y_ergonomia_para_musicos_evitar_lesiones,
  post_preguntas_de_entrevista_para_profesor_de_musica,
  post_preuniversitario_de_musica_que_es,
  post_primeras_clases_de_canto_que_esperar,
  post_primeros_ritmos_de_bateria,
  post_profesores_de_musica_para_jornada_complementaria,
  post_que_es_el_solfeo_y_como_practicarlo,
  post_que_es_la_armonia_musical,
  post_que_es_la_iniciacion_musical,
  post_que_es_un_intervalo_musical,
  post_que_instrumento_aprender_despues_de_los_60,
  post_que_instrumento_elegir_para_mi_hijo,
  post_regalos_musicales_para_ninos,
  post_repertorio_para_la_audicion_de_admision,
  post_respiracion_para_instrumentos_de_viento,
  post_ritmos_colombianos_bambuco_pasillo_y_cumbia_explicados,
  post_ritmos_de_guitarra_rasgueos_basicos,
  post_rubrica_de_evaluacion_docente_para_profesores_de_musica,
  post_rudimentos_de_bateria_para_principiantes,
  post_saxofon_alto_o_tenor_para_empezar,
  post_trompeta_o_trombon,
  post_verificaciones_antes_de_contratar_profesores_colombia,
  post_villancicos_faciles_para_aprender_en_navidad,
  post_violin_o_viola_diferencias,
  post_violin_o_violonchelo_cual_elegir,
  post_violin_para_ninos_guia_para_padres,
  post_voz_de_pecho_voz_de_cabeza_y_falsete,
];
